### ISSUE TITLE
Make SliceHeader fields pub?

### ISSUE THREAD

**Issue by petzeb** [dholroyd/h264-reader#39]
I am trying to use this crate to do some picture order calculations based on the 14496-10 spec.
In order to do that I need to access fields in the SliceHeader struct, so I was wondering if they could be made pub for access outside the crate? Or is there a reason why they are private at the moment?

**Comment by dholroyd** [comment]
The only reason they are private is that I wrote a bunch of parsing code but hadn't worked out what the public API of the type should be yet.  I haven't actually used the slice header data myself yet.

If you want access to specific fields, then I'd be happy to accept a patch that adds `pub` to the pieces you are after.  If utility methods might be preferable instead of direct field access I'd be happy to look at that too.

**Comment by petzeb** [comment]
Ok, makes sense. I will throw up a PR in a bit with the pieces that are needed for POC parsing.

**Comment by petzeb** [comment]
I made a PR:
https://github.com/dholroyd/h264-reader/pull/41
There are two commits there. The first one is just about making the fields needed pub.
The second commit is maybe more of an opinion piece. Curious what you think about it, mainly my reasoning about the `FieldsAbsolut` is that the field `bottom_delta` is a combination of the delta from the NAL and the pic_order_cnt_lsb which caused me a bit of confusion originally as it is no longer really a delta?

**Comment by petzeb** [comment]
Thanks for merging the PRs! Are you planning to make a new release including those as well?

**Comment by dholroyd** [comment]
Sorry for the delay - [here's 0.7.0](https://crates.io/crates/h264-reader/0.7.0).
