### ISSUE TITLE
Wrong Bounds Check for pic_parameter_set_id

### ISSUE THREAD

**Issue by wrv** [dholroyd/h264-reader#56]
The `pic_parameter_set_id` is a ParamSetId struct, which checks if the ID is within [0, 31]: https://github.com/dholroyd/h264-reader/blob/master/src/nal/pps.rs#L218

Valid bitstreams can have `pic_parameter_set_id`s in the range [0, 255].

**Comment by dholroyd** [comment]
This arises from mistakenly sharing a single `ParamSetId` type between `seq_parameter_set_rbsp()` and `pic_parameter_set_rbsp()` syntax.  Will need to break this into two separate Id types.

**Comment by astraw** [comment]
Is there a need for a video in which this gets triggered? I can provide one.

**Comment by dholroyd** [comment]
@astraw yes please - I would be happy to add a real PPS as a unit test

**Comment by astraw** [comment]
Here is [an MP4 file containing an h264 video track that triggers the issue for me](https://github.com/dholroyd/h264-reader/assets/30176/36c2b18a-c22f-4e0f-a9fa-96a485b2d843). (I moved my .h264 file into and .mp4 file with `ffmpeg -i movie20221006_115500.885150194-issue56.h264 -vcodec copy movie20221006_115500.885150194-issue56.mp4` because github didn't accept an .h264 upload. I verified the .h264 file extracted with `ffmpeg -i movie20221006_115500.885150194-issue56.mp4 -vcodec copy extract.h264` still triggers the issue for me.)
